"""Project metadata sources of truth."""

NAME = "myproject"
VERSION = "1.0.0"
DESCRIPTION = "PROJECT_DESCRIPTION_PLACEHOLDER"
AUTHOR = "AUTHOR_NAME_PLACEHOLDER"
AUTHOR_EMAIL = "AUTHOR_EMAIL_PLACEHOLDER"
